server:
  port: 8466
logging:
  file: /java/C2S_LOGS/provider-ui-api/provider-ui-api.log
info:
  component: Provider Ui Api
ribbon:
  ReadTimeout: 50000
hystrix.command.default.execution.timeout.enabled: false
security:
  oauth2:
    client:
      client-id: provider-ui-api
---
spring.profiles: standalone-ssl
spring:
  profiles:
    include: ssl-default
server:
  context-path: /provider-ui-api